### ISSUE TITLE
bug: invalid links for internal pages

### ISSUE THREAD

**Issue by robingenz** [pawamoy/mkdocs-llmstxt#10]
### Description of the bug

First of all: Thank you for this amazing project! My problem is: Links that refer to other pages of your own website are invalid.

**Example**:

```
# ML Kit Plugins

This is a list of our Capacitor ML Kit plugins:

- [Barcode Scanning](barcode-scanning/)
- [Face Detection](face-detection/)
- [Face Mesh Detection](face-mesh-detection/)
- [Selfie Segmentation](selfie-segmentation/)
- [Subject Segmentation](subject-segmentation/)
- [Translation](translation/)
```

**Source**: https://capawesome.io/plugins/mlkit/index.md

**Code**:

```
---
title: Capacitor ML Kit Plugins
---

# ML Kit Plugins

This is a list of our Capacitor ML Kit plugins:

- [Barcode Scanning](./barcode-scanning.md)
- [Face Detection](./face-detection.md)
- [Face Mesh Detection](./face-mesh-detection.md)
- [Selfie Segmentation](./selfie-segmentation.md)
- [Subject Segmentation](./subject-segmentation.md)
- [Translation](./translation.md)
```

### To Reproduce

1. Install the dependency: `pip install mkdocs-llmstxt`
2. Add configuration to `mkdocs.yml`:

```yml
- llmstxt:
      full_output: llms-full.txt
      markdown_description: Capawesome is an open source organization on [GitHub](https://github.com/capawesome-team) that provides enterprise-grade solutions and services for teams developing cross-platform applications with [Capacitor](https://github.com/ionic-team/capacitor). Capawesome currently maintains more than 50 high-quality [Capacitor Plugins](plugins/index.md) with more than **1,000,000 monthly downloads**. Besides that, Capawesome offers a [Cloud](cloud/index.md) solution for Capacitor Live Updates and a [Consulting](consulting.md) service for Capacitor-related projects.
      sections:
        Plugins:
          - plugins/*.md
        Cloud:
          - cloud/*.md
        Insiders:
          - insiders/*.md
        Consulting:
          - consulting.md
        Blog:
          - blog/*.md
```

(Sorry, the docs are not open-source)

### Full traceback

</details>

### Expected behavior

The `index.md` file should look like this:

```
# ML Kit Plugins

This is a list of our Capacitor ML Kit plugins:

- [Barcode Scanning](https://capawesome.io/plugins/mlkit/barcode-scanning/index.md)
- [Face Detection](https://capawesome.io/plugins/mlkit/face-detection/index.md)
- [Face Mesh Detection](https://capawesome.io/plugins/mlkit/face-mesh-detection/index.md)
- [Selfie Segmentation](https://capawesome.io/plugins/mlkit/selfie-segmentation/index.md)
- [Subject Segmentation](https://capawesome.io/plugins/mlkit/subject-segmentation/index.md)
- [Translation](https://capawesome.io/plugins/mlkit/translation/index.md)
```

### Environment information

I use the `ubuntu-latest` runner for building.
