### ISSUE TITLE
feature: Allow specifying page descriptions

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/mkdocs-llmstxt#6]
Mentioned in https://github.com/pawamoy/mkdocs-llmstxt/pull/4/files#r2003344450:

```yaml
plugins:
- llmstxt:
    markdown_description: Long description of my project
    sections:
      Usage documentation:
        - path: file1.md
          description: Desc
        - file2.md
```
